version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    ports:
      - '4002:80'
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - excalidraw-network

  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    ports:
      - '4001:4000'
    volumes:
      - ./data:/app/data
    environment:
      - PORT=4000
      - NODE_ENV=production
      - DB_PATH=/app/data/database.sqlite
    restart: unless-stopped
    networks:
      - excalidraw-network

networks:
  excalidraw-network:
    driver: bridge

volumes:
  data:
    driver: local
