services:
  excalidraw:
    image: ghcr.io/ozencb/excalidraw-persist:latest
    ports:
      - '4002:80' # Web client - change first number if needed
      - '4001:4000' # Server API - matches original setup
    volumes:
      - data:/app/data
    environment:
      - PORT=4000
      - NODE_ENV=production
      - DB_PATH=/app/data/database.sqlite
    restart: unless-stopped

volumes:
  data:
    driver: local
